default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DB_HOSTNAME"] %>
  port: <%= ENV["DB_PORT"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  timeout: 5000
  pool: <%= Integer(ENV.fetch("RAILS_MAX_THREADS") { 5 }) * Integer(ENV.fetch("WEB_CONCURRENCY") { 2 }) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>

development:
  <<: *default
  database: <%= "#{ENV["DB_NAME"]}_development" %>

test:
  <<: *default
  database: <%= "#{ENV["DB_NAME"]}_test" %>

staging:
  <<: *default
  database: <%= ENV["DB_NAME"] %>

production:
  <<: *default
  database: <%= ENV["DB_NAME"] %>